# Generated by Django 6.0.3 on 2026-04-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoAtualizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atualizacao', models.DateTimeField(auto_now_add=True)),
                ('registros_importados', models.IntegerField(default=0)),
                ('registros_atualizados', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('sucesso', 'Sucesso'), ('erro', 'Erro'), ('em_progresso', 'Em Progresso')], default='em_progresso', max_length=20)),
                ('mensagem_erro', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Histórico de Atualização',
                'verbose_name_plural': 'Históricos de Atualização',
                'ordering': ['-data_atualizacao'],
            },
        ),
        migrations.CreateModel(
            name='CasoNacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(help_text='Data do registro')),
                ('regiao', models.CharField(help_text='Região brasileira', max_length=50)),
                ('estado', models.CharField(help_text='Unidade Federativa (UF)', max_length=2)),
                ('municipio', models.CharField(blank=True, help_text='Município', max_length=100)),
                ('casos_confirmados', models.IntegerField(default=0, help_text='Números de casos confirmados')),
                ('casos_suspeitos', models.IntegerField(default=0, help_text='Números de casos suspeitos')),
                ('casos_descartados', models.IntegerField(default=0, help_text='Números de casos descartados')),
                ('obitos', models.IntegerField(default=0, help_text='Números de óbitos')),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('data_importacao', models.DateTimeField(auto_now_add=True)),
                ('origem_id', models.CharField(help_text='ID da API', max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Caso Nacional',
                'verbose_name_plural': 'Casos Nacionais',
                'ordering': ['-data'],
                'indexes': [models.Index(fields=['estado', '-data'], name='app_casonac_estado_b6bc8c_idx'), models.Index(fields=['regiao', '-data'], name='app_casonac_regiao_26a7f3_idx'), models.Index(fields=['-data'], name='app_casonac_data_d913ee_idx')],
            },
        ),
        migrations.CreateModel(
            name='ResumoRegional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(help_text='Data do registro')),
                ('regiao', models.CharField(help_text='Região brasileira', max_length=50)),
                ('total_casos_confirmados', models.IntegerField(default=0)),
                ('total_casos_suspeitos', models.IntegerField(default=0)),
                ('total_casos_descartados', models.IntegerField(default=0)),
                ('total_obitos', models.IntegerField(default=0)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resumo Regional',
                'verbose_name_plural': 'Resumos Regionais',
                'ordering': ['-data'],
                'unique_together': {('data', 'regiao')},
            },
        ),
    ]
